#!/usr/bin/env bash
# show a 404 error
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

touch 404.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;

   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default_page
sudo mv -f default /etc/nginx/sites-available/default_page
sudo service nginx restart
