#!/usr/bin/env bash
# show a 404 error
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;

   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default_page
sudo mv -f default_page /etc/nginx/sites-available/default
sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
