#!/usr/bin/env bash
#this script installs a haproxy software

# install
sudo apt -y update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null << EOF
frontend 191521-lb-01
    mode http
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 191521-web-01 35.153.193.254:80 check
    server 191521-web-02 3.83.253.141:80 check
EOF

# Enable HAProxy init script
sudo sed -i '$ a ENABLE=1' /etc/default/haproxy
# Restart HAProxy service
sudo service haproxy start
sudo service haproxy restart
