#!/usr/bin/env bash
#prints words if conditions are met
num=100
i=1
while ((i <= num))
do
	if [ "$((i % 15))" -eq 0 ]
	then
		echo "Fizz Buzz"
	elif [ "$((i % 3))" -eq 0 ]
	then
		echo "Fizz"
	elif [ "$((i % 5))" -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i+=1))
done
