#!/usr/bin/env bash
#prints words if conditions are true
num=10
i=0
while ((i < num))
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
