#!/usr/bin/env bash
#print words if conditons are met
num=20
i=1
while [ "$i" -le "$num" ]
do
	case $i in
		4)
		echo "$i"
		echo "bad luck from China"
		;;
		9)
		echo "$i"
		echo "bad luck from Japan"
		;;
		17)
		echo "$i"
		echo "bad luck from Italy"
		;;
		*)
		echo "$i"
	esac
	((i+=1))
done
