#!/usr/bin/env bash
#print hours and minutes
hour=0
i=0
num=12
while ((hour <= num))
do
	echo "Hour: $hour"
	if [ "$hour" -ne 12 ]
	then
		i=0
		while ((i < 60))
		do
			echo "$i"
			((i+=1))
		done
	fi
	((hour+=1))
done
